# Generated by Django 3.1.8 on 2021-05-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0005_auto_20210509_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=35)),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
            ],
        ),
    ]
