# Generated by Django 3.1.8 on 2021-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_service_providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=35)),
                ('address', models.CharField(default='', max_length=35)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(default='', max_length=35)),
                ('website', models.CharField(default='', max_length=35)),
                ('user', models.IntegerField(blank=True, default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
