# Generated by Django 3.1.8 on 2021-05-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0007_auto_20210513_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fname',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
        migrations.AlterField(
            model_name='t_dict',
            name='category',
            field=models.CharField(choices=[('Country', 'Country'), ('Header', 'Header'), ('Service Provider', 'Service Provider')], default='', max_length=20),
        ),
    ]
